<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>pega-integration</artifactId>
        <groupId>net.atos.aegoneb.pega</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>pega-dmz-esb</artifactId>
    <name>pega-dmz-esb</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <fuse.version>7.7.0.fuse-sb2-770010-redhat-00001</fuse.version>
        <spring-boot.version>2.1.6.RELEASE</spring-boot.version>
        <activemq-artemis.version>2.13.0.redhat-00006</activemq-artemis.version>

        <!-- java version -->
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

        <!-- maven plugin versions -->
        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version>

        <sonar.coverage.exclusions>
            src/main/java/net/atos/aegoneb/pega/dmz/cache/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/jms/amq/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/jms/ibmmq/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/file/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/mapping/**/*Configuration.java,
            src/main/java/net/atos/aegoneb/pega/dmz/route/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/transaction/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/Application.java,
            src/main/java/net/atos/aegoneb/pega/dmz/processor/AsyncPreProducerProcessorRegistry.java,
            src/main/java/net/atos/aegoneb/pega/dmz/processor/ReplyPrePoducerProcessorRegistry.java,
            src/main/java/net/atos/aegoneb/pega/dmz/processor/RouteConfigLoaderProcessorRegistry.java,
            src/main/java/net/atos/aegoneb/pega/dmz/processor/RequestPreProducerProcessorRegistry.java
        </sonar.coverage.exclusions>
        <sonar.cpd.exclusions>
            src/main/java/net/atos/aegoneb/pega/dmz/route/**/*.java,
            src/main/java/net/atos/aegoneb/pega/dmz/config/**/*.java
        </sonar.cpd.exclusions>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jboss.redhat-fuse</groupId>
                <artifactId>fuse-springboot-bom</artifactId>
                <version>${fuse.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
		 <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-bom</artifactId>
            <version>2.17.1</version>
            <scope>import</scope>
            <type>pom</type>
     </dependency> 
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
			  <exclusions>
			  <exclusion>
			  <groupId>org.slf4j</groupId>
			  <artifactId>log4j-over-slf4j</artifactId>
			</exclusion>
		  </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-caffeine-starter</artifactId>
        </dependency>
        <dependency>
			<groupId>org.apache.camel</groupId>
			<artifactId>camel-ftp-starter</artifactId>
		</dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-hazelcast-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jms-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>activemq-jms-pool</artifactId>
            <version>5.11.0.redhat-630446</version>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-jms-client</artifactId>
            <version>${activemq-artemis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-commons</artifactId>
            <version>${activemq-artemis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-core-client</artifactId>
            <version>${activemq-artemis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>artemis-selector</artifactId>
            <version>${activemq-artemis.version}</version>
        </dependency>

        <dependency>
            <groupId>com.ibm.mq</groupId>
            <artifactId>com.ibm.mq.allclient</artifactId>
            <version>9.1.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.hawt</groupId>
            <artifactId>hawtio-springboot</artifactId>
            <version>2.0.0.fuse-sb2-770008-redhat-00001</version>
        </dependency>
        <dependency>
            <groupId>org.messaginghub</groupId>
            <artifactId>pooled-jms</artifactId>
            <version>1.1.1.redhat-00003</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.1</version>
        </dependency>


        <!-- JUnit -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-test-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>pl.pragmatists</groupId>
            <artifactId>JUnitParams</artifactId>
            <version>1.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>java-hamcrest</artifactId>
            <version>2.0.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.4.1.redhat-3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
        <groupId>com.github.tomakehurst</groupId>
        <artifactId>wiremock</artifactId>
        <version>1.58</version>
        <scope>test</scope>
        </dependency>

    </dependencies>
    <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>net/atos/aegoneb/pega/dmz/cache/**/*</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/jms/amq/**/*</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/jms/ibmmq/**/*</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/mapping/**/*Configuration.class</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/route/**/*</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/transaction/**/*</exclude>
                        <exclude>net/atos/aegoneb/pega/dmz/Application.class</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jboss.redhat-fuse</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${fuse.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>redhat maven repository ga</id>
            <url>https://maven.repository.redhat.com/ga/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>redhat maven repository ga plugin</id>
            <url>https://maven.repository.redhat.com/ga/</url>
        </pluginRepository>
    </pluginRepositories>
</project>
